name: Scheduled Continuous Integration

on:
  pull_request:

jobs:
  jruby28:
    runs-on: ubuntu-22.04
    services:
      elasticsearch7:
        image: elasticsearch:7.16.2
        env:
          discovery.type: single-node
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      elasticsearch8:
        image: elasticsearch:8.4.2
        env:
          discovery.type: single-node
          xpack.security.enabled: false
        ports:
          - 9250:9200
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      memcached:
        image: memcached:latest
        ports:
          - 11211:11211
        options: >-
          --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/udp/127.0.0.1/11211'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mongodb:
        image: mongo:5.0.11
        ports:
          - 27017:27017
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - "3306:3306"
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q check_port_connectivity"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      # matrix:
        # multiverse: [agent, background, background_2, database, frameworks, httpclients, httpclients_2, rails, rest]
    steps:
      - name: Set the default Java version
        run: sudo update-alternatives --set java ${JAVA_HOME_8_X64}/bin/java &&
             sudo update-alternatives --set javac ${JAVA_HOME_8_X64}/bin/javac &&
             java -version &&
             javac -version

      - name: Configure git
        run: 'git config --global init.defaultBranch main'

      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Install JRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: jruby-9.3.9.0
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-8-jdk-amd64

      - name: Bundle
        run: bundle install
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-8-jdk-amd64

      - name: multiverse alone
        run: jruby -v; bundle exec rake test:multiverse[net_http,verbose]
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          SERIALIZE: 1
          JRUBY_OPTS: --dev --debug
          JAVA_HOME: /usr/lib/jvm/temurin-8-jdk-amd64

      - name: Run Multiverse Tests
        # uses: nick-invision/retry@v1.0.0
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 1
          command: bundle exec rake test:multiverse[net_http,verbose]
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          SERIALIZE: 1
          JRUBY_OPTS: --dev --debug
          JAVA_HOME: /usr/lib/jvm/temurin-8-jdk-amd64

      - name: Annotate errors
        if: ${{ failure() }}
        uses: ./.github/actions/annotate

  # jruby104:
  #   runs-on: ubuntu-22.04
  #   services:
  #     elasticsearch7:
  #       image: elasticsearch:7.16.2
  #       env:
  #         discovery.type: single-node
  #       ports:
  #         - 9200:9200
  #       options: >-
  #         --health-cmd "curl http://localhost:9200/_cluster/health"
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 10
  #     elasticsearch8:
  #       image: elasticsearch:8.4.2
  #       env:
  #         discovery.type: single-node
  #         xpack.security.enabled: false
  #       ports:
  #         - 9250:9200
  #       options: >-
  #         --health-cmd "curl http://localhost:9200/_cluster/health"
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 10
  #     memcached:
  #       image: memcached:latest
  #       ports:
  #         - 11211:11211
  #       options: >-
  #         --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/udp/127.0.0.1/11211'"
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #     mongodb:
  #       image: mongo:5.0.11
  #       ports:
  #         - 27017:27017
  #     mysql:
  #       image: mysql:5.7
  #       env:
  #         MYSQL_ALLOW_EMPTY_PASSWORD: yes
  #       options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
  #       ports:
  #         - "3306:3306"
  #     postgres:
  #       image: postgres:latest
  #       ports:
  #         - 5432:5432
  #     rabbitmq:
  #       image: rabbitmq:latest
  #       ports:
  #         - 5672:5672
  #       options: >-
  #         --health-cmd "rabbitmq-diagnostics -q check_port_connectivity"
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #     redis:
  #       image: redis
  #       ports:
  #         - 6379:6379
  #       options: >-
  #         --health-cmd "redis-cli ping"
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #   strategy:
  #     fail-fast: false
  #     # matrix:
  #       # multiverse: [agent, background, background_2, database, frameworks, httpclients, httpclients_2, rails, rest]
  #   steps:
  #     - name: Set the default Java version
  #       run: sudo update-alternatives --set java ${JAVA_HOME_8_X64}/bin/java &&
  #            sudo update-alternatives --set javac ${JAVA_HOME_8_X64}/bin/javac &&
  #            java -version &&
  #            javac -version

  #     - name: Configure git
  #       run: 'git config --global init.defaultBranch main'

  #     - name: Check out the source code
  #       uses: actions/checkout@v3

  #     - name: Install JRuby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: jruby-9.3.9.0
  #       env:
  #         JAVA_HOME: /usr/lib/jvm/temurin-8-jdk-amd64

  #     - name: Bundle
  #       run: bundle install
  #       env:
  #         JAVA_HOME: /usr/lib/jvm/temurin-8-jdk-amd64

  #     - name: Run Multiverse Tests
  #       # uses: nick-invision/retry@v1.0.0
  #       uses: nick-fields/retry@v1.0.4
  #       with:
  #         timeout_minutes: 60
  #         max_attempts: 1
  #         command:  jruby -v; bundle exec rake test:multiverse[net_http,verbose]
  #       env:
  #         DB_PORT: ${{ job.services.mysql.ports[3306] }}
  #         SERIALIZE: 1
  #         JRUBY_OPTS: --dev --debug
  #         JAVA_HOME: /usr/lib/jvm/temurin-8-jdk-amd64

  #     - name: Annotate errors
  #       if: ${{ failure() }}
  #       uses: ./.github/actions/annotate

  jruby104:
    runs-on: ubuntu-22.04
    services:
      elasticsearch7:
        image: elasticsearch:7.16.2
        env:
          discovery.type: single-node
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      elasticsearch8:
        image: elasticsearch:8.4.2
        env:
          discovery.type: single-node
          xpack.security.enabled: false
        ports:
          - 9250:9200
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      memcached:
        image: memcached:latest
        ports:
          - 11211:11211
        options: >-
          --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/udp/127.0.0.1/11211'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mongodb:
        image: mongo:5.0.11
        ports:
          - 27017:27017
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - "3306:3306"
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q check_port_connectivity"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      # matrix:
        # multiverse: [agent, background, background_2, database, frameworks, httpclients, httpclients_2, rails, rest]
    steps:
      - name: Set the default Java version
        run: sudo update-alternatives --set java ${JAVA_HOME_8_X64}/bin/java &&
             sudo update-alternatives --set javac ${JAVA_HOME_8_X64}/bin/javac &&
             java -version &&
             javac -version

      - name: Configure git
        run: 'git config --global init.defaultBranch main'

      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Install JRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: jruby-9.3.9.0
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-8-jdk-amd64

      - name: Bundle
        run: bundle install
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-8-jdk-amd64

      - name: Run Multiverse Tests
        run: ./.github/workflows/scripts/retry_command
        env:
          TEST_CMD: "bundle exec rake test:multiverse[net_http,verbose]"
          RETRY_ATTEMPS: 2
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          SERIALIZE: 1
          JRUBY_OPTS: --dev --debug
          JAVA_HOME: /usr/lib/jvm/temurin-8-jdk-amd64

      - name: Annotate errors
        if: ${{ failure() }}
        uses: ./.github/actions/annotate


